# AMOTD 插件配置文件
# 支持颜色代码，使用 & 符号
# 例如: &a - 亮绿色, &b - 青色, &c - 红色, 等等

# MOTD 第一行
line1: "&a欢迎来到 &b我的 &cMinecraft &d服务器！"

# MOTD 第二行
line2: "&e这是由 &6AMOTD &7插件 &8生成的消息"

# 是否启用服务器图标显示
enable_server_icon: true 