name: AMOTD
version: 1.0
main: cn.mcobs.bukkit.AMOTD
api-version: 1.16
authors:
  - xiaoren
description: 一个简单的MOTD自定义插件

commands:
  amotd:
    description: AMOTD插件命令
    usage: /amotd <reload|get>
    permission: amotd.admin

permissions:
  amotd.admin:
    description: 允许使用 AMOTD 高级命令
    default: true
  amotd.command.reload:
    description: 允许重载插件配置
    default: op
  amotd.command.get:
    description: 允许获取预设MOTD样式
    default: op 