name: AMOTD
version: 1.1
main: cn.mcobs.bukkit.AMOTD
api-version: 1.16
authors:
  - xiaoren
description: A simple MOTD customization plugin

commands:
  amotd:
    description: AMOTD plugin commands
    usage: /amotd <reload|get>
    permission: amotd.admin

permissions:
  amotd.admin:
    description: Allows access to AMOTD advanced commands
    default: true
  amotd.command.reload:
    description: Allows reloading the plugin configuration
    default: op
  amotd.command.get:
    description: Allows getting preset MOTD styles
    default: op 