name: Java CI with Maven

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build with Java ${{ matrix.java-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8, 11, 17]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven (Java ${{ matrix.java-version }})
      run: mvn -B package --file pom.xml
    
    - name: Upload artifact (Java ${{ matrix.java-version }})
      if: matrix.java-version == 8
      uses: actions/upload-artifact@v4
      with:
        name: AMOTD-Java${{ matrix.java-version }}-${{ github.sha }}
        path: target/AMOTD-*.jar